program = expr*

expr = <ws> (atom | compound) <ws>

<compound> = list

list = <"("> expr* <")">

<atom> = number / boolean / ignore / keyword / symbol

number = #"\d+"

boolean = "#t" | "#f"

ignore = "#_"

keyword = <":"> symbol

symbol = #"[!?+\-\*/%@#\w]+"

<ws> = #"(\s|;[^\n]*\n)*"
